### ISSUE TITLE
GitHub Login Authentication

### ISSUE THREAD

**Issue by divyanshu-rawat** [systers/slack-systers-opensource#10]
## Description
As a Systers community member, I need to revise existing way of joining [Systers Open Source Slack Inviter](http://systers.io/slack-systers-opensource/) by authenticating users via Github.
For More Information on this please refer, [Arizona Web Dev](https://azwebdevs.org/signin) uses GitHub to authorize.

## Mocks
N.A

### Update [Required]
- [ ] Investigate How you will achieve this?
- [ ] Allowing User to Authenticate via  GITHUB.
### Enhancement to Update [Optional]
- [ ] Fell free to add your Ideas.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Follow AnitaB.org Brand guidelines.
- [ ] Approval by 1 mentor.

## Estimation
 N.A

**Comment by bethanyr** [comment]
is this issue a duplicate of https://github.com/systers/slack-systers-opensource/issues/21? Can it be closed?

**Comment by BaaniLeen** [comment]
@bethanyr Yes. Yes :)

**Comment by BaaniLeen** [comment]
@bethanyr Can we please close this issue? Thanks! :)

**Comment by bethanyr** [comment]
Closing this issue since it is a duplicate and has been implemented.
