### ISSUE TITLE
Update Terms and Conditions, Code of Conduct, Privacy policies.

### ISSUE THREAD

**Issue by BaaniLeen** [systers/slack-systers-opensource#31]
## Description
As a contributor,
I need add a scrollable div for TnC.

### Update [Required]
- [ ] Update to a checkbox with the following text/links:
By checking this box, I affirm that I have read and accept to be bound by the AnitaB.org [Code of Conduct](https://ghc.anitab.org/code-of-conduct/), [Terms](https://anitab.org/terms-of-use/), and [Privacy Policy](https://anitab.org/privacy-policy/). Further, I consent to the use of my information for the stated purpose.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours 

@Janiceilene Can you assign me the issue? :)

**Comment by ExactlyMay** [comment]
I'll adjust this issue to update the privacy policy, etc.
