### ISSUE TITLE
Add Footer on Slack Inviter

### ISSUE THREAD

**Issue by BaaniLeen** [systers/slack-systers-opensource#45]
## Description
As a contributor,
I need to add footer.

### Update [Required]
- [ ] Will update later

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours 

@Janiceilene @ancyp Can you please assign me the issue? Thanks :)

**Comment by Tharangi** [comment]
Closing this issue since already the PRs related to the issue has been merged.
