### ISSUE TITLE
Revamp index.html

### ISSUE THREAD

**Issue by shreyateeza** [systers/slack-systers-opensource#7]
## Description
As a Systers community member,
I need to revamp the index.html,
so that it can provide much better user interface and experience.

## Mocks
![slack-inviter](https://user-images.githubusercontent.com/30488330/36945495-f0461b16-1fd4-11e8-9aee-9fe1d8b42cc8.png)

### Update [Required]
- [ ] Create a captcha.
- [ ] Create a "Code of Conduct" agreement.
- [ ] Create a GitHub login authentication.
 
### Enhancement to Update [Optional]
- [ ] Add alternate method to get slack invite, in case, the person does not have a github account.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
20 hours

**Comment by shreyateeza** [comment]
@MeepyMay Please review this issue and let me know if any amendments are required.

**Comment by anumehaagrawal** [comment]
@shreyateeza @may Can I work on this issue as my mock up is ready?
@shreyateeza  In case you have already done your mock up , we can discuss our ideas and maybe come up with a good UI for the same

**Comment by shreyateeza** [comment]
@anumehaagrawal Yes I am working in this issue. The work has already. Basic structure is about to complete. As you can see I am waiting for @may to review this issue and let me know if she wants any change in the mock up. :)

**Comment by shreyateeza** [comment]
@prachi1210 Please review this issue and let me know if any amendments are required.

**Comment by BaaniLeen** [comment]
@ancyp @Janiceilene @bethanyr Can we close this issue? I don't have access to close this issue since I have not created it!
